log:
  log_dir: '/kaggle/working/log'
  chkpt_dir: '/kaggle/working/chkpt'


arcface:
  chkpt_path: '/kaggle/input/backbone.pth'
  vector_size: 512

data:
  dataset_dir: '/kaggle/input/ffhq-1024x1024'
  valset_dir: '/kaggle/input/celebahq-resized-256x256'

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 16

  num_workers: 16
  grad_clip: 0.0
